version: '3'

services:
  db:
    image: mysql:8
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./:/var/www
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
    ports: 
      - 3306:3306
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    networks:
      - wordpress

  schemaspy:
    build: ./docker/schemaspy
    depends_on:
      - db
    container_name: schemaspy
    volumes:
      - ./docker/schemaspy/output:/output
      - ./docker/schemaspy/config:/config
    command: -t mysql -host db:3306 -db wordpress -u wordpress -p wordpress -s wordpress
    networks:
      - wordpress

  schemaspy-server:
    image: nginx
    depends_on:
      - schemaspy
    container_name: schemaspy-server
    ports:
      - "8888:80"
    volumes:
      - ./docker/schemaspy/output:/usr/share/nginx/html:ro
    networks:
      - wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
       - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./src:/var/www/html
    networks:
      - wordpress

volumes:
  db_data:
    driver: local

networks:
  wordpress:
    external: true